/**
 * 主题词包 · 每个主题手挑约 30 个常用词
 *
 * 词列表与 Supabase 中的实际词形必须严格一致才能匹配。
 * 服务端用 .in("word", words) 一次性查出，前端展示能查到的。
 */

export type Theme = {
  slug: string;
  emoji: string;
  color: string;
  nameZh: string;
  nameEn: string;
  descZh: string;
  descEn: string;
  words: string[];
};

export const THEMES: Theme[] = [
  {
    slug: "ielts-speaking",
    emoji: "🗣️",
    color: "from-blue-400 to-blue-600",
    nameZh: "雅思口语",
    nameEn: "IELTS Speaking",
    descZh: "Part 1-3 高频万能词，让答题更流利地道",
    descEn: "High-frequency anchor words for IELTS Part 1-3",
    words: [
      "absolutely",
      "basically",
      "definitely",
      "certainly",
      "exactly",
      "eventually",
      "honestly",
      "amazing",
      "awesome",
      "fantastic",
      "brilliant",
      "wonderful",
      "terrific",
      "awful",
      "nowadays",
      "generally",
      "recently",
      "lately",
      "usually",
      "occasionally",
      "imagine",
      "suppose",
      "assume",
      "believe",
      "consider",
      "prefer",
      "recommend",
      "regarding",
      "despite",
      "however",
      "moreover",
    ],
  },
  {
    slug: "study-abroad",
    emoji: "✈️",
    color: "from-violet-400 to-violet-600",
    nameZh: "留学场景",
    nameEn: "Study Abroad",
    descZh: "申请、入学、生活全流程关键词",
    descEn: "Key terms across application, enrollment and overseas life",
    words: [
      "accommodation",
      "application",
      "deposit",
      "scholarship",
      "tuition",
      "dormitory",
      "registration",
      "orientation",
      "semester",
      "thesis",
      "dissertation",
      "plagiarism",
      "internship",
      "transcript",
      "recommendation",
      "lecture",
      "seminar",
      "tutorial",
      "adapt",
      "integrate",
      "culture",
      "abroad",
      "foreign",
      "visa",
      "embassy",
      "citizenship",
      "homesick",
      "campus",
      "graduate",
      "undergraduate",
    ],
  },
  {
    slug: "business",
    emoji: "💼",
    color: "from-amber-400 to-orange-500",
    nameZh: "商务英语",
    nameEn: "Business English",
    descZh: "会议、谈判、营销、汇报必备词汇",
    descEn: "Vocabulary for meetings, negotiations, marketing and reporting",
    words: [
      "agenda",
      "deadline",
      "schedule",
      "proposal",
      "negotiation",
      "contract",
      "stakeholder",
      "revenue",
      "profit",
      "budget",
      "expense",
      "invoice",
      "marketing",
      "branding",
      "customer",
      "client",
      "retention",
      "conversion",
      "meeting",
      "presentation",
      "conference",
      "headquarters",
      "branch",
      "strategy",
      "growth",
      "target",
      "quota",
      "performance",
      "evaluation",
      "feedback",
    ],
  },
  {
    slug: "academic-writing",
    emoji: "📚",
    color: "from-emerald-400 to-teal-600",
    nameZh: "学术写作",
    nameEn: "Academic Writing",
    descZh: "论文写作、论证、分析的高频词",
    descEn: "Words for academic writing, argument and analysis",
    words: [
      "analyze",
      "hypothesis",
      "methodology",
      "evidence",
      "conclusion",
      "paradigm",
      "empirical",
      "qualitative",
      "quantitative",
      "significance",
      "validity",
      "reliability",
      "furthermore",
      "moreover",
      "however",
      "nevertheless",
      "consequently",
      "hence",
      "demonstrate",
      "indicate",
      "illustrate",
      "examine",
      "evaluate",
      "assess",
      "contribute",
      "emphasize",
      "propose",
      "conduct",
      "investigate",
      "establish",
    ],
  },
];

export function findTheme(slug: string): Theme | undefined {
  return THEMES.find((t) => t.slug === slug);
}
